[package]
name = "linux-keymapper"
version = "0.1.0"
authors = ["MonstrousOgre <monstrousogre0813@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev-rs = "0.4.0"
libudev = "0.3"
directories = "3.0.1"
